Update nixos/nix docker image used on CircleCI
Because both CircleCI jobs (cabal-test and nix-build) failed with:

error: evaluation aborted with the following error message: '
       This version of Nixpkgs requires an implementation of Nix with the following features:
       - `builtins.nixVersion` reports at least 2.18

       You are evaluating with Nix 2.13.2, please upgrade:

       - If you are running NixOS, `nixos-rebuild' can be used to upgrade your system.

       - Alternatively, with Nix > 2.0 `nix upgrade-nix' can be used to imperatively
         upgrade Nix. You may use `nix-env --version' to check which version you have.

       - If you installed Nix using the install script (https://nixos.org/nix/install),
         it is safe to upgrade by running it again:

             curl -L https://nixos.org/nix/install | sh

       For more information, please see the NixOS release notes at
       https://nixos.org/nixos/manual or locally at
       /nix/store/i936ws2xplkqgbzkxkacqqq2dpag3ndf-source/nixos/doc/manual/release-notes.

       If you need further help, see https://nixos.org/nixos/support.html