Actually run tests when running `nix run .#cabal-test`
Without `--enable-tests` flag to `cabal test` we get:

```
Error: [Cabal-7043]
Cannot test the package fec-0.2.0 because none of the components are
available to build: the test suite 'tests' is not available because
the solver picked a plan that does not include the test suites,
perhaps because no such plan exists. To see the error message
explaining the problems with such plans, force the solver to include
the test suites for all packages, by adding the line 'tests: True' to
the 'cabal.project.local' file.
```

This is apparently because we do not have a cabal.project or
cabal.project.local with a `tests: True` line.