Run `nix develop --command cabal test` on CircleCI
Since `nix run .#cabal-test` (a flake app) runs in a sandbox without
network access, it does not have access to Hackage, so it fails with:

```
Warning: The package list for 'hackage.haskell.org' does not exist. Run 'cabal
update' to download it.
Resolving dependencies...
Error: [Cabal-7107]
Could not resolve dependencies:
[__0] trying: fec-0.2.0 (user goal)
[__1] unknown package: extra (dependency of fec)
[__1] fail (backjumping, conflict set: extra, fec)
After searching the rest of the dependency tree exhaustively, these were the goals I've had most trouble fulfilling: fec, extra

Exited with code exit status 1
```